Configutation:
  name: Default
  status: warn

  Appenders:
    Console:
      name: CONSOLE
      target: SYSTEM_OUT
      PatternLayout:
        pattern: "%highlight{%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}}{faint} %highlight{%5p} %highlight{${PID:- }}{magenta} %highlight{---}{faint} %highlight{[%20.20t]}{faint} %highlight{%-40.40logger{39}}{cyan} %highlight{:}{faint} %m%n%wEx"

  Loggers:
    Root:
      level: info
      AppenderRef:
        - ref: CONSOLE
    Logger:
      - name: "com.naonworks"
        additivity: false
        level: ALL
        AppenderRef:
          - ref: CONSOLE